FROM payara/server-full:6.2023.2-jdk17
ENV JACOCO_URL http://search.maven.org/remotecontent?filepath=org/jacoco/jacoco/0.7.9/jacoco-0.7.9.zip
ENV JACOCO_FILENAME jacoco-0.7.9.zip
#RUN mkdir JaCoCo && \
#  wget ${JACOCO_URL} -O ${JACOCO_FILENAME} && unzip ${JACOCO_FILENAME} -d JaCoCo && \
#  chmod -R 755 JaCoCo